#
# sensors ...
#
[[filter]]
  Name = "FBA-ES-T-BASALT"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "FBA-ES-T"
    Frequency   = 1.0
    Gain   = 0.254712175
    Scale  = 1.0
    InputUnits  = "M/S**2"
    OutputUnits = "V"

[[filter]]
  Name = "FBA-ES-T-DECK"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "FBA-ES-T"
    Frequency   = 1.0
    Gain   = 0.1273560875
    Scale  = 1.0
    InputUnits  = "M/S**2"
    OutputUnits = "V"

[[filter]]
  Name = "FBA-23-DECK"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "FBA-ES-T"
    Frequency   = 1.0
    Gain   = 0.1273560875
    Scale  = 1.0
    InputUnits  = "M/S**2"
    OutputUnits = "V"

[[filter]]
  Name = "SDP"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "SDP"
    Frequency   = 1.0
    Gain   = 0.1273560875
    Scale  = 1.0
    InputUnits  = "M/S**2"
    OutputUnits = "V"

[[filter]]
  Name = "SSA-320"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "SSA-320"
    Frequency   = 1.0
    Gain   = 0.1273560875
    Scale  = 1.0
    InputUnits  = "M/S**2"
    OutputUnits = "V"

[[filter]]
  Name = "CUSP SENSOR"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "CUSP"
    Frequency   = 1.0
    Gain   = 0.10197162129779282425
    Scale  = 1.0
    InputUnits  = "M/S**2"
    OutputUnits = "V"

[[filter]]
  Name = "270-600/12V"

  [[filter.stage]]
    Type   = "poly"
    Lookup = "270-600/12V"
    Scale  = 1.0
    InputUnits  = "hPa"
    OutputUnits = "V"

[[filter]]
  Name = "L4C"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "L4C"
    Frequency   = 15.0
    Gain   = 177.8
    Scale  = 1.0
    InputUnits  = "M/S"
    OutputUnits = "V"

[[filter]]
  Name = "LE-3Dlite"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "LE-3Dlite"
    Frequency   = 15.0
    Gain   = 400.0
    Scale  = 1.0
    InputUnits  = "M/S"
    OutputUnits = "V"

[[filter]]
  Name = "LE-3DliteMkII"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "LE-3DliteMkII"
    Frequency   = 15.0
    Gain   = 400.0
    Scale  = 1.0
    InputUnits  = "M/S"
    OutputUnits = "V"

[[filter]]
  Name = "2_Hz_Duke_Malin_Seismometer"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "MALIN"
    Frequency   = 15.0
    Gain   = 62.2
    Scale  = 1.0
    InputUnits  = "M/S"
    OutputUnits = "V"

#
# dataloggers
#
[[filter]]
  Name = "Q330_FLbelow100-100"

  [[filter.stage]]
    Type = "a2d"
    SampleRate     = 100.0
    Gain     = 419430.4
    InputUnits    = "V"
    OutputUnits   = "COUNTS"

  [[filter.stage]]
    Type   = "fir"
    Lookup = "Q330_FLbelow100-100"
    SampleRate   = 100.0
    Delay  = 0.04167
    Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "Q330_FLbelow100-200-PREAMP"

  [[filter.stage]]
    Type        = "paz"
    Lookup      = "Q330-PREAMP"
    Frequency   = 15.0
    Gain        = 30.0
    Scale       = 1.0
    InputUnits  = "V"
    OutputUnits = "V"
  [[filter.stage]]
    Type        = "a2d"
    Lookup      = "A2D"
    Decimate    = 1
    SampleRate  = 200.0
    Gain        = 419430.4
    InputUnits  = "V"
    OutputUnits = "COUNTS"
  [[filter.stage]]
    Type        = "fir"
    Lookup      = "Q330_FLbelow100-200"
    SampleRate  = 200.0
    Delay       = 0.020462
    Correction  = 0.020462
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "Q330_FLbelow100-200"

  [[filter.stage]]
    Type     = "a2d"
    Lookup   = "A2D"
    Decimate = 1
    SampleRate     = 200.0
    Gain     = 419430.4
    InputUnits    = "V"
    OutputUnits   = "COUNTS"
  [[filter.stage]]
    Type   = "fir"
    Lookup = "Q330_FLbelow100-200"
    SampleRate   = 200.0
    Delay  = 0.020462
    Correction  = 0.020462
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "Q330S+_FLbelow100-100-PREAMP32"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "Q330-PREAMP"
    Frequency   = 15.0
    Gain   = 32.0
    Scale  = 1.0
    InputUnits  = "V"
    OutputUnits = "V"
  [[filter.stage]]
    Type     = "a2d"
    Lookup   = "A2D"
    Decimate = 1
    SampleRate     = 100.0
    Gain     = 419430.4
    InputUnits    = "V"
    OutputUnits   = "COUNTS"
  [[filter.stage]]
    Type   = "fir"
    Lookup = "Q330S+_FLbelow100-100"
    SampleRate   = 100.0
    Delay  = 0.04167
    Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "Q330S+_FLbelow100-1"

  [[filter.stage]]
    Type        = "a2d"
    Lookup      = "A2D"
    Decimate    = 1
    SampleRate  = 1.0
    Gain        = 419430.4
    InputUnits  = "V"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "Q330S+_FLbelow100-1"
    SampleRate  = 1.0
    Delay       = 15.930462
    Correction  = 15.930462
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "Q330S+_FLbelow100-100"

  [[filter.stage]]
    Type        = "a2d"
    Lookup      = "A2D"
    Decimate    = 1
    SampleRate  = 100.0
    Gain        = 419430.4
    InputUnits  = "V"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "Q330S+_FLbelow100-100"
    SampleRate  = 100.0
    Delay       = 0.04167
    Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "EARSS-50"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "EARSS-GAIN"
    Frequency   = 15.0
    Gain   = 1.0
    Scale  = 1.0
    InputUnits  = "V"
    OutputUnits = "V"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "EARSS-50Hz"
    Frequency   = 15.0
    Gain   = 1.0
    Scale  = 1.0
    InputUnits  = "V"
    OutputUnits = "V"

  [[filter.stage]]
    Type        = "a2d"
    Lookup      = "A2D"
    Decimate    = 1
    SampleRate  = 50.0
    Gain        = 104857.60
    InputUnits  = "V"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "EARSS-100"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "EARSS-GAIN"
    Frequency   = 15.0
    Gain   = 1.0
    Scale  = 1.0
    InputUnits  = "V"
    OutputUnits = "V"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "EARSS-100Hz"
    Frequency   = 15.0
    Gain   = 1.0
    Scale  = 1.0
    InputUnits  = "V"
    OutputUnits = "V"

  [[filter.stage]]
    Type        = "a2d"
    Lookup      = "A2D"
    Decimate    = 1
    SampleRate  = 100.0
    Gain        = 104857.60
    InputUnits  = "V"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "ALTUS-200"

  [[filter.stage]]
    Type        = "a2d"
    Lookup      = "A2D"
    Decimate    = 1
    SampleRate  = 2000.0
    Gain        = 3355443.2
    InputUnits  = "V"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "ALTUS_A200"
    SampleRate  = 400.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "ALTUS_BNC"
    SampleRate  = 200.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "CUSP-200"

  [[filter.stage]]
    Type        = "a2d"
    Lookup      = "A2D"
    Decimate    = 1
    SampleRate  = 200.0
    Gain        = 1000000.0
    InputUnits  = "V"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "BASALT-50"

  [[filter.stage]]
    Type        = "a2d"
    Lookup      = "A2D"
    Decimate    = 1
    SampleRate  = 30000.0
    Gain        = 1677721.6
    InputUnits  = "V"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "BASALT_A5-50-S5C"
    SampleRate  = 6000.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "BASALT_A3-50"
    SampleRate  = 2000.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "BASALT_A4-50"
    SampleRate  = 500.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "BASALT_A5-50"
    SampleRate  = 100.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "BASALT_B2-80"
    SampleRate  = 50.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

[[filter]]
  Name = "BASALT-200"

  [[filter.stage]]
    Type        = "a2d"
    Lookup      = "A2D"
    Decimate    = 1
    SampleRate  = 30000.0
    Gain        = 1677721.6
    InputUnits  = "V"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "BASALT_A5-50-S5C"
    SampleRate  = 6000.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "BASALT_A3-50"
    SampleRate  = 2000.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "BASALT_A5-50"
    SampleRate  = 400.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"

  [[filter.stage]]
    Type        = "fir"
    Lookup      = "BASALT_B2-80"
    SampleRate  = 200.0
    #Delay       = 0.04167
    #Correction  = 0.04167
    InputUnits  = "COUNTS"
    OutputUnits = "COUNTS"
