[[sensor]]
  Model = "2 Hz Duke Malin Seismometer"
  Type = "Short Period Borehole Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "270-600/12V"
  Type = "Barometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "270-600/24V"
  Type = "Barometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "270-800/12V"
  Type = "Barometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "4.5 Hz Duke Malin Seismometer"
  Type = "Short Period Borehole Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3ESP"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3ESP-Z"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3ESPC"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3T"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3TB"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3TB-GN"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-40T-30S"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-40T-60S"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-6T"
  Type = "Accelerometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CUSP-Me SENSOR"
  Type = "Building Array Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3A SENSOR"
  Type = "Strong Motion Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3B SENSOR"
  Type = "Strong Motion Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3C SENSOR"
  Type = "Strong Motion Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3C3 SENSOR"
  Type = "Strong Motion Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3D SENSOR"
  Type = "Strong Motion Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSPM SENSOR"
  Type = "Strong Motion Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "Druck PTX-1830"
  Type = "Pressure Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "Druck PTX-1830-LAND"
  Type = "Pressure Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "FBA-23-DECK"
  Type = "Accelerometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 180.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 90.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 270.0
    Dip = 0.0

[[sensor]]
  Model = "FBA-ES-T"
  Type = "Accelerometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "FBA-ES-T-BASALT"
  Type = "Accelerometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "FBA-ES-T-DECK"
  Type = "Accelerometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "FBA-ES-T-ISO"
  Type = "Accelerometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "GS-11D seismometer"
  Type = "Short Period Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "IESE HS-1-LT Mini 4.5Hz"
  Type = "Short Period Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "IESE S10g-4.5 (with preamp)"
  Type = "Short Period Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "IESE S10g-4.5 (without preamp)"
  Type = "Short Period Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "IESE S31f-15 (with preamp)"
  Type = "Short Period Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "InfraBSU microphone"
  Type = "Mirophone"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "Kinemetrics SBEPI"
  Type = "Accelerometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "L4C"
  Type = "Short Period Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "L4C-3D"
  Type = "Short Period Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "LE-3Dlite"
  Type = "Short Period Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "LE-3DliteMkII"
  Type = "Short Period Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "LM35"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "Nanometrics Trillium 120QA"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "SDP"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "SSA-320"
  Type = "Strong Motion Sensor"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "STS-2"
  Type = "Broadband Seismometer"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.pin]]
    Pin = 1
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.pin]]
    Pin = 2
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "Scout Hydrophone"
  Type = "Hydrophone"

  [[sensor.pin]]
    Pin = 0
    Azimuth = 0.0
    Dip = 0.0
