[[response]]

  [[response.sensors]]
    Sensors  = ["2 Hz Duke Malin Seismometer"]
    Filters  = ["2_Hz_Duke_Malin_Seismometer"]
    Channels = "Z12"
    Reversed = true

  [[response.dataloggers]]
    Dataloggers = ["Q330S/3", "Q330S/6"]
    Type          = "CG"
    Label         = "EH"
    Rate          = 100.0
    Frequencey    = 15.0
    StorageFormat = "Steim2"
    ClockDrift    = 0.0001
    Filters       = ["Q330S+_FLbelow100-100-PREAMP32"]

[[response]]

  [[response.sensors]]
    Sensors     = ["L4C"]
    Filters     = ["L4C"]
    Channels    = "Z"
    Reversed    = false

  [[response.sensors]]
    Sensors     = ["L4C-3D"]
    Filters     = ["L4C"]
    Channels    = "ZNE"
    Reversed    = false

  [[response.sensors]]
    Sensors     = ["LE-3Dlite"]
    Filters     = ["LE-3Dlite"]
    Channels    = "ZNE"
    Reversed    = false

  [[response.sensors]]
    Sensors     = ["LE-3DliteMkII"]
    Filters     = ["LE-3DliteMkII"]
    Channels    = "ZNE"
    Reversed    = false

  [[response.dataloggers]]
    Dataloggers   = ["Q330/3", "Q330/6"]
    Type          = "CG"
    Label         = "EH"
    Rate          = 100.0
    Frequencey    = 15.0
    StorageFormat = "Steim2"
    ClockDrift    = 0.0001
    Filters       = ["Q330_FLbelow100-100"]
    Skip         = "KQ03"

  [[response.dataloggers]]
    Dataloggers   = ["Q330/3", "Q330/6"]
    Type          = "CG"
    Label         = "EH"
    Rate          = 200.0
    Frequencey    = 15.0
    StorageFormat = "Steim2"
    ClockDrift    = 0.0001
    Filters       = ["Q330_FLbelow100-200"]
    Match          = "KQ03"
