[[sensor]]
  Model = "2 Hz Duke Malin Seismometer"
  Type = "Short Period Borehole Seismometer"
  Description = "Duke Malin"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "270-600/12V"
  Type = "Barometer"
  Description = "Setra 270"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "270-600/24V"
  Type = "Barometer"
  Description = "Setra 270"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "270-800/12V"
  Type = "Barometer"
  Description = "Setra 270"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "4.5 Hz Duke Malin Seismometer"
  Type = "Short Period Borehole Seismometer"
  Description = "Duke Malin"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3ESP"
  Type = "Broadband Seismometer"
  Description = "CMG-3ESP"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3ESP-Z"
  Type = "Broadband Seismometer"
  Description = "CMG-3ESP"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3ESPC"
  Type = "Broadband Seismometer"
  Description = "CMG-3ESP"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3T"
  Type = "Broadband Seismometer"
  Description = "CMG-3T"
  Manufacturer = "Guralp"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3TB"
  Type = "Broadband Seismometer"
  Description = "CMG-3T"
  Manufacturer = "Guralp"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-3TB-GN"
  Type = "Broadband Seismometer"
  Description = "CMG-3T"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-40T-30S"
  Type = "Broadband Seismometer"
  Description = "CMG-40T"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-40T-60S"
  Type = "Broadband Seismometer"
  Description = "CMG-40T"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CMG-6T"
  Type = "Accelerometer"
  Description = "CMG-6T"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "CUSP-Me SENSOR"
  Type = "Building Array Sensor"
  Description = "CUSP Me"

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3A SENSOR"
  Type = "Strong Motion Sensor"
  Description = "CUSP 3A"

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3B SENSOR"
  Type = "Strong Motion Sensor"
  Description = "CUSP 3B"

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3C SENSOR"
  Type = "Strong Motion Sensor"
  Description = "CUSP 3C"

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3C3 SENSOR"
  Type = "Strong Motion Sensor"
  Description = "CUSP 3C"

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSP3D SENSOR"
  Type = "Strong Motion Sensor"
  Description = "CUSP 3D"

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "CUSPM SENSOR"
  Type = "Strong Motion Sensor"
  Description = "CUSP M"

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "Druck PTX-1830"
  Type = "Pressure Sensor"
  Description = "Druck PTX"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "Druck PTX-1830-LAND"
  Type = "Pressure Sensor"
  Description = "Druck PTX"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "FBA-23-DECK"
  Type = "Accelerometer"
  Description = "FBA-23"

  [[sensor.component]]
    Azimuth = 180.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 90.0

  [[sensor.component]]
    Azimuth = 270.0
    Dip = 0.0

[[sensor]]
  Model = "FBA-ES-T"
  Type = "Accelerometer"
  Description = "FBA-ES-T"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "FBA-ES-T-BASALT"
  Type = "Accelerometer"
  Description = "FBA-ES-T"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "FBA-ES-T-DECK"
  Type = "Accelerometer"
  Description = "FBA-ES-T"

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "FBA-ES-T-ISO"
  Type = "Accelerometer"
  Description = "FBA-ES-T"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "GS-11D seismometer"
  Type = "Short Period Seismometer"
  Description = "GS-11D"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "IESE HS-1-LT Mini 4.5Hz"
  Type = "Short Period Seismometer"
  Description = "HS1-1-LT"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "IESE S10g-4.5 (with preamp)"
  Type = "Short Period Seismometer"
  Description = "S10g-4.5"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "IESE S10g-4.5 (without preamp)"
  Type = "Short Period Seismometer"
  Description = "S10g-4.5"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "IESE S31f-15 (with preamp)"
  Type = "Short Period Seismometer"
  Description = "S31f-15"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "InfraBSU microphone"
  Type = "Mirophone"
  Description = "InfraBSU"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "Kinemetrics SBEPI"
  Type = "Accelerometer"
  Description = "SBEPI"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "L4C"
  Type = "Short Period Seismometer"
  Description = "L4C"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "L4C-3D"
  Type = "Short Period Seismometer"
  Description = "L4C-3D"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "LE-3Dlite"
  Type = "Short Period Seismometer"
  Description = "LE-3Dlite"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "LE-3DliteMkII"
  Type = "Short Period Seismometer"
  Description = "LE-3DliteMkII"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "LM35"
  Description = "LM35"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

[[sensor]]
  Model = "Nanometrics Trillium 120QA"
  Type = "Broadband Seismometer"
  Description = "Trillium 120"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "SDP"
  Description = "SDP"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "SSA-320"
  Type = "Strong Motion Sensor"
  Description = "SSA-320"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

[[sensor]]
  Model = "STS-2"
  Type = "Broadband Seismometer"
  Description = "STS-2"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = -90.0

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0

  [[sensor.component]]
    Azimuth = 90.0
    Dip = 0.0

[[sensor]]
  Model = "Scout Hydrophone"
  Type = "Hydrophone"
  Description = "Scout"

  [[sensor.component]]
    Azimuth = 0.0
    Dip = 0.0
