sudo: required

services:
  - docker

language: go

go:
  - 1.5

install: true

script:
  - ./test.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
          
# vim: set ts=2 sw=2 tw=0 et:
