sudo: required

services:
  - docker

language: go

go:
  - 1.7

install: true

script:
  - ./test.sh

deploy:
     - provider: s3
       skip_cleanup: true
       access_key_id: AKIAJ7KAYTEDAR345M7A
       secret_access_key:
         secure: CEU38LANOevDCsDOeM9I9uLwyWneW8lkNTJQc58ZzIThCqSJ9zpbUW+k4tWWPg5yZYtQ8nudB17Z+WuteMCialr+ZbApn2DaCEgczL27/SRwyA5GMfLBVXIPW+1BpBvspHbwk9X1l+RdVOllr+5uVjq/gdhBhHYTrVht4+DNSJ3pr4IZU4r8E5p+7q0m/8ocQv+ED9suaBJH37ujiz17YV86q3KTRHn8MW9sCpzPb/xiXPPpj/ZP3I2Cd7M48UvjlBNAdCJdrH45h7ThIM4Ezwii3x20XSxp/ROL+buGARn8qxgGDBgAKuBjGKnYjvQHqYh0LN91LUrJElnefp2CRA2/JgdmTxQoQ4vG++0RRmJifWnnoPzHZJKJscoxYvUmkYIuRLFc/ZJZ5i3KnKyDSD4qTZ+/3dUDyCYxP3fTyYgcyno/SXF8V21KU9GLjlyTgxs/A2heotvW8SAHDfSd03hT9PHkeVbnuIzpSipHhNIkwPiKbvTtE0uaa+M/lkVtOR0Z2Pmc9L1cHFtZd6vuX9WwEN4LNN0e48TmrLyJjx9JlG5YWX+NIl7mLCtlVA3Mqg1UKdIvFDhpUq3gOfMzAEMRgBnZwQYK3ghrjCg/8+P1V6AjP1hbTe0YPTYVoJ8NClhQ29kfkdpIsRc0YhV8pUh30DHAqRpC2YeYpF3xPWU=
       bucket: api.geonet.org.nz
       region: ap-southeast-2
       local_dir: .tmp/api/delta
       upload-dir: delta
       on:
          branch: master
     - provider: script
       script: ./deploy.sh
       on:
         branch: master

# vim: set ts=2 sw=2 tw=0 et:
