[[filter]]
  Name = "2_Hz_Duke_Malin_Seismometer"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "MALIN"
    Freq   = 15.0
    Gain   = 62.2
    Scale  = 1.0
    Input  = "M/S"
    Output = "V"

[[filter]]
  Name = "Q330_FLbelow100-100"

  [[filter.stage]]
    Type = "a2d"
    Lookup = "A2D"
    Decimate = 1
    Rate     = 100.0
    Gain     = 419430.4
    Input    = "V"
    Output   = "COUNTS"
  [[filter.stage]]
    Type   = "fir"
    Lookup = "Q330_FLbelow100-100"
    Rate   = 100.0
    Delay  = 0.04167
    Corr   = 0.04167
    Input  = "COUNTS"
    Output = "COUNTS"

[[filter]]
  Name = "Q330_FLbelow100-200-PREAMP"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "Q330-PREAMP"
    Freq   = 15.0
    Gain   = 30.0
    Scale  = 1.0
    Input  = "V"
    Output = "V"
  [[filter.stage]]
    Type     = "a2d"
    Lookup   = "A2D"
    Decimate = 1
    Rate     = 200.0
    Gain     = 419430.4
    Input    = "V"
    Output   = "COUNTS"
  [[filter.stage]]
    Type   = "fir"
    Lookup = "Q330_FLbelow100-200"
    Rate   = 200.0
    Delay  = 0.020462
    Corr   = 0.020462
    Input  = "COUNTS"
    Output = "COUNTS"

[[filter]]
  Name = "Q330_FLbelow100-200"

  [[filter.stage]]
    Type     = "a2d"
    Lookup   = "A2D"
    Decimate = 1
    Rate     = 200.0
    Gain     = 419430.4
    Input    = "V"
    Output   = "COUNTS"
  [[filter.stage]]
    Type   = "fir"
    Lookup = "Q330_FLbelow100-200"
    Rate   = 200.0
    Delay  = 0.020462
    Corr   = 0.020462
    Input  = "COUNTS"
    Output = "COUNTS"

[[filter]]
  Name = "Q330S+_FLbelow100-100-PREAMP32"

  [[filter.stage]]
    Type   = "paz"
    Lookup = "Q330-PREAMP"
    Freq   = 15.0
    Gain   = 32.0
    Scale  = 1.0
    Input  = "V"
    Output = "V"
  [[filter.stage]]
    Type     = "a2d"
    Lookup   = "A2D"
    Decimate = 1
    Rate     = 100.0
    Gain     = 419430.4
    Input    = "V"
    Output   = "COUNTS"
  [[filter.stage]]
    Type   = "fir"
    Lookup = "Q330S+_FLbelow100-100"
    Rate   = 100.0
    Delay  = 0.04167
    Corr   = 0.04167
    Input  = "COUNTS"
    Output = "COUNTS"
