[[polynomial]]
  Name = "270-600/12V"
  Gain = 0.01
  ApproximationType = "MACLAURIN"
  FrequencyLowerBound = 0.0
  FrequencyUpperBound = 0.0
  ApproximationLowerBound = 600.0
  ApproximationUpperBound = 1100.0
  MaximumError = 0.0

  [[polynomial.coefficient]]
    Value = 600.0

  [[polynomial.coefficient]]
    Value = 100.0

[[polynomial]]
  Name = "270-600/24V"
  Gain = 0.01
  ApproximationType = "MACLAURIN"
  FrequencyLowerBound = 0.0
  FrequencyUpperBound = 0.0
  ApproximationLowerBound = 600.0
  ApproximationUpperBound = 1100.0
  MaximumError = 0.0

  [[polynomial.coefficient]]
    Value = 600.0

  [[polynomial.coefficient]]
    Value = 100.0

[[polynomial]]
  Name = "270-800/12V"
  Gain = 0.016666666666666666
  ApproximationType = "MACLAURIN"
  FrequencyLowerBound = 0.0
  FrequencyUpperBound = 0.0
  ApproximationLowerBound = 800.0
  ApproximationUpperBound = 1100.0
  MaximumError = 0.0

  [[polynomial.coefficient]]
    Value = 800.0

  [[polynomial.coefficient]]
    Value = 60.0

[[polynomial]]
  Name = "Druck PTX-1830-A"
  Gain = 0.0008
  ApproximationType = "MACLAURIN"
  FrequencyLowerBound = 0.0
  FrequencyUpperBound = 0.0
  ApproximationLowerBound = 0.0
  ApproximationUpperBound = 20.0
  MaximumError = 0.0

  [[polynomial.coefficient]]
    Value = 0.004

  [[polynomial.coefficient]]
    Value = 0.0008

[[polynomial]]
  Name = "Druck PTX-1830-B"
  Gain = 250.0
  ApproximationType = "MACLAURIN"
  FrequencyLowerBound = 0.0
  FrequencyUpperBound = 0.0
  ApproximationLowerBound = 0.004
  ApproximationUpperBound = 0.02
  MaximumError = 0.0

  [[polynomial.coefficient]]
    Value = 0.0

  [[polynomial.coefficient]]
    Value = 250.0

[[polynomial]]
  Name = "InfraBSU microphone"
  Gain = 0.008
  ApproximationType = "MACLAURIN"
  FrequencyLowerBound = 0.0
  FrequencyUpperBound = 0.0
  ApproximationLowerBound = 0.0
  ApproximationUpperBound = 0.0
  MaximumError = 0.0
  Notes = "this is incorrect, enough to get a plot\nin theory this is linear with +/- 10mV for +/- 125Pa (1.25 mbar)\n which translates to +/- 1V for +/- 125mbar\n"

  [[polynomial.coefficient]]
    Value = 0.0

  [[polynomial.coefficient]]
    Value = 125.0

[[polynomial]]
  Name = "LM35"
  Gain = 0.01
  ApproximationType = "MACLAURIN"
  FrequencyLowerBound = 0.0
  FrequencyUpperBound = 0.0
  ApproximationLowerBound = -55.0
  ApproximationUpperBound = 150.0
  MaximumError = 0.0

  [[polynomial.coefficient]]
    Value = 0.0

  [[polynomial.coefficient]]
    Value = 100.0

[[polynomial]]
  Name = "SEAWATER"
  Gain = 1.03
  ApproximationType = "MACLAURIN"
  FrequencyLowerBound = 0.0
  FrequencyUpperBound = 0.0
  ApproximationLowerBound = 0.0
  ApproximationUpperBound = 20.0
  MaximumError = 0.0

  [[polynomial.coefficient]]
    Value = 0.0

  [[polynomial.coefficient]]
    Value = 1.03
