[[response]]
  #Dataloggers = ["Q330/3", "Q330/6"]
  #Sensors = ["LE-3Dlite"]
  #Reversed = false
  #Lookup = "Q330_LE-3Dlite"

[[response]]
  #Dataloggers = ["Q330/3", "Q330/6"]
  #Sensors = ["LE-3DliteMkII"]
  #Reversed = false
  #Lookup = "Q330_LE-3DliteMkII"
  #Match = "!KQ03"

[[response]]
  #Dataloggers = ["Q330/6"]
  #Sensors = ["LE-3DliteMkII"]
  #Reversed = false
  #Lookup = "Q330_LE-3DliteMkII_200"
  #Match = "KQ03"

[[response]]
  #Dataloggers = ["Q330/6"]
  #Sensors = ["L4C-3D"]
  #Reversed = false
  #Lookup = "Q330_L4C-3D"

[[response]]
  #Dataloggers = ["Q330/6"]
  #Sensors = ["GS-11D seismometer"]
  #Reversed = false
  lookup = "Q330_GS-11D_seismometer"

[[response]]
  #Dataloggers = ["Q330S/3", "Q330S/6"]
  #Sensors = ["2 Hz Duke Malin Seismometer", "4.5 Hz Duke Malin Seismometer"]
  #Reversed = true
  Lookup = "Q330S_Duke_Malin_Seismometer"
