[[stream]]
  Name = "Q330_FLbelow100-100"
  Rate = 100
  [[stream.stage]]
        Type = "a2d"
        Lookup = "A2D"
        Decimate = 1
        Rate     = 100.0
        Gain     = 419430.4
        Input    = "V"
        Output   = "COUNTS"
  [[stream.stage]]
        Type   = "fir"
        Lookup = "Q330_FLbelow100-100"
        Rate   = 100.0
        Delay  = 0.04167
        Corr   = 0.04167
        Input  = "COUNTS"
        Output = "COUNTS"

[[stream]]
  Name = "Q330_FLbelow100-200-PREAMP"
  Rate = 200
  [[stream.stage]]
        Type   = "paz"
        Lookup = "Q330-PREAMP"
        Freq   = 15.0
        Gain   = 30.0
        Scale  = 1.0
        Input  = "V"
        Output = "V"
  [[stream.stage]]
        Type     = "a2d"
        Lookup   = "A2D"
        Decimate = 1
        Rate     = 200.0
        Gain     = 419430.4
        Input    = "V"
        Output   = "COUNTS"
  [[stream.stage]]
        Type   = "fir"
        Lookup = "Q330_FLbelow100-200"
        Rate   = 200.0
        Delay  = 0.020462
        Corr   = 0.020462
        Input  = "COUNTS"
        Output = "COUNTS"

[[stream]]
  Name = "Q330_FLbelow100-200"
  Rate = 200
  [[stream.stage]]
        Type     = "a2d"
        Lookup   = "A2D"
        Decimate = 1
        Rate     = 200.0
        Gain     = 419430.4
        Input    = "V"
        Output   = "COUNTS"
  [[stream.stage]]
        Type   = "fir"
        Lookup = "Q330_FLbelow100-200"
        Rate   = 200.0
        Delay  = 0.020462
        Corr   = 0.020462
        Input  = "COUNTS"
        Output = "COUNTS"
